services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_app.wsgi:application
    staticPublishPath: staticfiles  # Directorio donde se encuentran los archivos estáticos recopilados
