# Generated by Django 5.1.1 on 2024-12-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_itemcarrito_carrito_and_more'),
        ('ventas', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrito',
            new_name='CarritoItem',
        ),
    ]
