# Generated by Django 5.1.1 on 2024-12-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_itemcarrito_carritoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
