# Generated by Django 5.1.1 on 2024-12-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
